/*
 * Terrier Remote API
 * This is an API to allow a client to search a remote index with Terrier
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 2133815j@student.gla.ac.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.terrier.remote.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.terrier.remote.model.KeyValue;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;

/**
 * RemoteIndex
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-02-03T11:07:24.149Z")
public class RemoteIndex   {
  @JsonProperty("path")
  private String path = null;

  @JsonProperty("prefix")
  private String prefix = null;

  @JsonProperty("indexName")
  private String indexName = null;

  @JsonProperty("props")
  private List<KeyValue> props = new ArrayList<KeyValue>();

  public RemoteIndex path(String path) {
    this.path = path;
    return this;
  }

  /**
   * Get path
   * @return path
   **/
  @JsonProperty("path")
  @ApiModelProperty(example = "C:/path/to/index", required = true, value = "")
  @NotNull
  public String getPath() {
    return path;
  }

  public void setPath(String path) {
    this.path = path;
  }

  public RemoteIndex prefix(String prefix) {
    this.prefix = prefix;
    return this;
  }

  /**
   * Get prefix
   * @return prefix
   **/
  @JsonProperty("prefix")
  @ApiModelProperty(example = "data", required = true, value = "")
  @NotNull
  public String getPrefix() {
    return prefix;
  }

  public void setPrefix(String prefix) {
    this.prefix = prefix;
  }

  public RemoteIndex indexName(String indexName) {
    this.indexName = indexName;
    return this;
  }

  /**
   * the name under which the index will be stored and accessed
   * @return indexName
   **/
  @JsonProperty("indexName")
  @ApiModelProperty(example = "firstIndex", required = true, value = "the name under which the index will be stored and accessed")
  @NotNull
  public String getIndexName() {
    return indexName;
  }

  public void setIndexName(String indexName) {
    this.indexName = indexName;
  }

  public RemoteIndex props(List<KeyValue> props) {
    this.props = props;
    return this;
  }

  public RemoteIndex addPropsItem(KeyValue propsItem) {
    this.props.add(propsItem);
    return this;
  }

  /**
   * Get props
   * @return props
   **/
  @JsonProperty("props")
  @ApiModelProperty(required = true, value = "")
  @NotNull
  public List<KeyValue> getProps() {
    return props;
  }

  public void setProps(List<KeyValue> props) {
    this.props = props;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RemoteIndex remoteIndex = (RemoteIndex) o;
    return Objects.equals(this.path, remoteIndex.path) &&
            Objects.equals(this.prefix, remoteIndex.prefix) &&
            Objects.equals(this.indexName, remoteIndex.indexName) &&
            Objects.equals(this.props, remoteIndex.props);
  }

  @Override
  public int hashCode() {
    return Objects.hash(path, prefix, indexName, props);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RemoteIndex {\n");

    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    prefix: ").append(toIndentedString(prefix)).append("\n");
    sb.append("    indexName: ").append(toIndentedString(indexName)).append("\n");
    sb.append("    props: ").append(toIndentedString(props)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

